[package]
name = "bwinf_aufgabe_5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
colored = "2.0.0"
itertools = "0.10.5"
petgraph = "0.6.2"
shared = { path = "../shared" }
